server:
  port: 8080
spring:
  profiles:
    active: local
  application:
    name: Bitrix24
    url: http://localhost:8080
    fe-url: http://localhost:5174 
    ngrok-url: https://kangaroo-cute-halibut.ngrok-free.app  
bitrix:
  client-id: #<Your Client ID>
  client-secret: #<Your Client Secret>
  domain: #<Your Bitrix24 Domain>